config/routes.rb
Rails.application.routes.draw do
  resources :reports
  root 'reports#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  validates :event_id, uniqueness: true
  validates :event_id, :browser, :domain, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:event_id, :browser, :domain)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Jar Intro</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= yield %>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- <script src="js/bootstrap.min.js"></script> -->
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_for(report) do |f| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %>
    <%= f.number_field :event_id %>
  </div>

  <div class="field">
    <%= f.label :browser %>
    <%= f.text_field :browser %>
  </div>

  <div class="field">
    <%= f.label :domain %>
    <%= f.text_field :domain %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h2>Reports</h2>
  <p>Search result</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Event</th>
        <th>Browser</th>
        <th>Domain</th>
        <th>Created</th>
        <!--<th colspan="3"></th>-->
      </tr>
    </thead>

    <tbody>
      <% @reports.each do |report| %>
        <tr>
          <td><%= report.id %></td>
          <td><%= report.event_id %></td>
          <td><%= report.browser %></td>
          <td><%= report.domain %></td>
          <td><%= report.created_at.to_date %></td>
          <!--<td><%= link_to 'Show', report %></td>-->
          <!--<td><%= link_to 'Edit', edit_report_path(report) %></td>-->
          <!--<td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Report', new_report_path %>
</div>
<br>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/search.erb
<div class="container">
  <div class="checkbox">
    <label><input type="checkbox" value="">Event id</label>
  </div>
  <div class="checkbox">
    <label><input type="checkbox" value="">Domain</label>
  </div>
  <div class="checkbox disabled">
    <label><input type="checkbox" value="" disabled>Browser</label>
  </div>
</div>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @report.event_id %>
</p>

<p>
  <strong>Browser:</strong>
  <%= @report.browser %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @report.domain %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>